#server:
#    port: 8081

#kafka.url: localhost:9092

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    tdcr.notification: DEBUG
    org.apache.kafka: INFO
    com.amazonaws: INFO
  file: logs/notify.log
  pattern:
    console:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"